[tool.poetry]
name = "skeleton"
version = "0.1.0"
description = ""
authors = ["zachvalenta <zjv5002@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.1"
python-dotenv = "^0.10.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
httpie = "^1.0.3"
coverage = "^5.0.2"
pytest = "^5.3.2"
flake8 = "^3.7.9"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
